"""
feeds_curated.py — Auto-generated by audit_feeds.py
Generated: 2026-03-21
Only feeds active in the last 30 days are included.
"""

# Each entry: (name, url, sector)
# Sector values: "ai-updates" | "ai-business" | "ai-dev" | "security"

FEEDS = [
    #  AI Updates: model releases, research, product launches ──────────────────
    ("404 Media"                                     , "https://www.404media.co/rss"                                                             , "ai-updates"),  # 0d ago
    ("Ahead of AI"                                   , "https://magazine.sebastianraschka.com/feed"                                              , "ai-updates"),  # 24d ago
    ("AI 2 People"                                   , "https://ai2people.com/feed/"                                                             , "ai-updates"),  # 1d ago
    ("AI Accelerator Institute"                      , "https://aiacceleratorinstitute.com/rss/"                                                 , "ai-updates"),  # 2d ago
    ("AI for Good Blog"                              , "https://aiforgood.itu.int/feed/"                                                         , "ai-updates"),  # 12d ago
    ("AI Insider"                                    , "https://theaiinsider.tech/feed/"                                                         , "ai-updates"),  # 0d ago
    ("AI News"                                       , "https://www.artificialintelligence-news.com/feed/"                                       , "ai-updates"),  # 2d ago
    ("AI Snake Oil"                                  , "https://aisnakeoil.substack.com/feed"                                                    , "ai-updates"),  # 25d ago
    ("AI Time Journal"                               , "https://www.aitimejournal.com/feed/"                                                     , "ai-updates"),  # 2d ago
    ("AI Weekly"                                     , "https://aiweekly.co/issues.rss"                                                          , "ai-updates"),  # 1d ago
    ("AI – SiliconANGLE"                             , "https://siliconangle.com/category/ai/feed"                                               , "ai-updates"),  # 6d ago
    ("AIhub"                                         , "https://aihub.org/feed/?cat=-473"                                                        , "ai-updates"),  # 1d ago
    ("AIhub"                                         , "https://aihub.org/feed?cat=-473"                                                         , "ai-updates"),  # 1d ago
    ("AIModels.fyi"                                  , "https://aimodels.substack.com/feed"                                                      , "ai-updates"),  # 0d ago
    ("Apple ML"                                      , "https://machinelearning.apple.com/rss.xml"                                               , "ai-updates"),  # 3d ago
    ("Ars Technica"                                  , "https://feeds.arstechnica.com/arstechnica/index"                                         , "ai-updates"),  # 0d ago
    ("Ars Technica - AI"                             , "https://arstechnica.com/ai/feed/"                                                        , "ai-updates"),  # 0d ago
    ("Artificial Intelligence – Futurism"            , "https://futurism.com/categories/ai-artificial-intelligence/feed"                         , "ai-updates"),  # 0d ago
    ("Artificial Intelligence – TechRepublic"        , "https://www.techrepublic.com/rssfeeds/topic/artificial-intelligence/"                    , "ai-updates"),  # 0d ago
    ("Artificial intelligence – The Conversation (EU)", "https://theconversation.com/europe/topics/artificial-intelligence-ai-90/articles.atom"   , "ai-updates"),  # 1d ago
    ("AWS News Blog - AI"                            , "https://aws.amazon.com/blogs/aws/category/artificial-intelligence/feed/"                 , "ai-updates"),  # 5d ago
    ("Berkeley AI (BAIR)"                            , "https://bair.berkeley.edu/blog/feed.xml"                                                 , "ai-updates"),  # 8d ago
    ("Big Data – SiliconANGLE"                       , "https://siliconangle.com/category/big-data/feed"                                         , "ai-updates"),  # 10d ago
    ("Chain of Thought (every.to)"                   , "https://every.to/chain-of-thought/feed.xml"                                              , "ai-updates"),  # 1d ago
    ("Cisco Blogs - AI"                              , "https://blogs.cisco.com/ai/feed"                                                         , "ai-updates"),  # 2d ago
    ("Clarifai Blog"                                 , "https://www.clarifai.com/blog/rss.xml"                                                   , "ai-updates"),  # 3d ago
    ("CMU ML Blog"                                   , "https://blog.ml.cmu.edu/feed"                                                            , "ai-updates"),  # 3d ago
    ("Cogito Tech Blog"                              , "https://www.cogitotech.com/feed/"                                                        , "ai-updates"),  # 1d ago
    ("Computational Intelligence (Blogspot)"         , "http://computational-intelligence.blogspot.com/feeds/posts/default"                      , "ai-updates"),  # 1d ago
    ("Copyleaks Blog"                                , "https://copyleaks.com/blog/feed"                                                         , "ai-updates"),  # 2d ago
    ("DataRobot Blog"                                , "https://www.datarobot.com/blog/feed/"                                                    , "ai-updates"),  # 2d ago
    ("DeepMind Blog"                                 , "https://deepmind.com/blog/feed/basic/"                                                   , "ai-updates"),  # 4d ago
    ("Department of Product"                         , "https://departmentofproduct.substack.com/feed"                                           , "ai-updates"),  # 1d ago
    ("Digital Thought Disruption"                    , "https://digitalthoughtdisruption.com/feed/"                                              , "ai-updates"),  # 28d ago
    ("Dxcover Blog"                                  , "https://www.dxcover.com/feed/"                                                           , "ai-updates"),  # 18d ago
    ("EE Times"                                      , "https://www.eetimes.com/feed"                                                            , "ai-updates"),  # 0d ago
    ("Engadget"                                      , "https://www.engadget.com/rss.xml"                                                        , "ai-updates"),  # 0d ago
    ("Fusemachines Insights"                         , "https://insights.fusemachines.com/feed/"                                                 , "ai-updates"),  # 8d ago
    ("gHacks Technology News"                        , "https://www.ghacks.net/feed/"                                                            , "ai-updates"),  # 0d ago
    ("Gizmodo"                                       , "https://gizmodo.com/rss"                                                                 , "ai-updates"),  # 0d ago
    ("Google Blog AI"                                , "https://blog.google/technology/ai/rss/"                                                  , "ai-updates"),  # 4d ago
    ("Google DeepMind"                               , "https://deepmind.google/blog/rss.xml"                                                    , "ai-updates"),  # 4d ago
    ("Google Research"                               , "https://research.google/blog/rss/"                                                       , "ai-updates"),  # 3d ago
    ("GPTZero Blog"                                  , "https://gptzero.me/news/rss/"                                                            , "ai-updates"),  # 5d ago
    ("HealthTech Magazine"                           , "https://feeds.feedburner.com/HealthTechMagazine"                                         , "ai-updates"),  # 0d ago
    ("Import AI (Beehiiv)"                           , "https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml"                                            , "ai-updates"),  # 1d ago
    ("Import AI (Jack Clark)"                        , "https://importai.substack.com/feed"                                                      , "ai-updates"),  # 5d ago
    ("Isentia"                                       , "https://www.isentia.com/feed/"                                                           , "ai-updates"),  # 24d ago
    ("Just AI News"                                  , "https://justainews.com/feed/"                                                            , "ai-updates"),  # 0d ago
    ("Last Week in AI"                               , "https://lastweekin.ai/feed"                                                              , "ai-updates"),  # 5d ago
    ("Live Science - AI"                             , "https://www.livescience.com/feeds/tag/artificial-intelligence"                           , "ai-updates"),  # 2d ago
    ("Machine learning – Nature"                     , "https://www.nature.com/subjects/machine-learning.rss"                                    , "ai-updates"),  # 0d ago
    ("Marek Rosa / GoodAI Blog"                      , "https://blog.marekrosa.org/feed/"                                                        , "ai-updates"),  # 2d ago
    ("MarkTechPost"                                  , "https://www.marktechpost.com/feed/"                                                      , "ai-updates"),  # 0d ago
    ("MIRI Blog"                                     , "https://intelligence.org/feed/"                                                          , "ai-updates"),  # 1d ago
    ("MIT AI News"                                   , "https://news.mit.edu/rss/topic/artificial-intelligence2"                                 , "ai-updates"),  # 1d ago
    ("MIT News – Machine Learning"                   , "https://news.mit.edu/topic/mitmachine-learning-rss.xml"                                  , "ai-updates"),  # 2d ago
    ("MIT Tech Review"                               , "https://www.technologyreview.com/feed/"                                                  , "ai-updates"),  # 1d ago
    ("MIT Tech Review AI"                            , "https://www.technologyreview.com/topic/artificial-intelligence/feed/"                    , "ai-updates"),  # 1d ago
    ("Netflix Technology Blog – Medium"              , "https://medium.com/feed/@netflixtechblog"                                                , "ai-updates"),  # 15d ago
    ("New Scientist – Technology"                    , "https://www.newscientist.com/subject/technology/feed/"                                   , "ai-updates"),  # 0d ago
    ("News on AI/ML – TechXplore"                    , "https://techxplore.com/rss-feed/machine-learning-ai-news/"                               , "ai-updates"),  # 0d ago
    ("News on AI/ML – TechXplore (phys.org)"         , "https://phys.org/rss-feed/technology-news/machine-learning-ai/"                          , "ai-updates"),  # 0d ago
    ("NVIDIA Blog"                                   , "https://feeds.feedburner.com/nvidiablog"                                                 , "ai-updates"),  # 1d ago
    ("O'Reilly Media - AI & ML"                      , "https://www.oreilly.com/radar/topics/ai-ml/feed/index.xml"                               , "ai-updates"),  # 1d ago
    ("ODSC – Medium"                                 , "https://medium.com/feed/@odsc"                                                           , "ai-updates"),  # 2d ago
    ("One Useful Thing"                              , "https://www.oneusefulthing.org/feed"                                                     , "ai-updates"),  # 9d ago
    ("OpenAI Blog"                                   , "https://openai.com/news/rss.xml"                                                         , "ai-updates"),  # 2d ago
    ("PetaPixel"                                     , "https://petapixel.com/feed"                                                              , "ai-updates"),  # 0d ago
    ("Quanta Magazine"                               , "https://api.quantamagazine.org/feed"                                                     , "ai-updates"),  # 1d ago
    ("Qudata"                                        , "https://qudata.com/en/news/rss.xml"                                                      , "ai-updates"),  # 8d ago
    ("Robot Writers AI"                              , "https://robotwritersai.com/feed/"                                                        , "ai-updates"),  # 5d ago
    ("Robotics Research News – ScienceDaily"         , "https://www.sciencedaily.com/rss/computers_math/robotics.xml"                            , "ai-updates"),  # 3d ago
    ("SAS - AI"                                      , "https://blogs.sas.com/content/topic/artificial-intelligence/feed/"                       , "ai-updates"),  # 1d ago
    ("Science News - AI"                             , "https://www.sciencenews.org/topic/artificial-intelligence/feed"                          , "ai-updates"),  # 9d ago
    ("ScienceDaily - AI News"                        , "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml"             , "ai-updates"),  # 3d ago
    ("Scientific American"                           , "http://rss.sciam.com/ScientificAmerican-Global"                                          , "ai-updates"),  # 0d ago
    ("Shaip Blog"                                    , "https://www.shaip.com/feed/"                                                             , "ai-updates"),  # 11d ago
    ("Spritle Blog"                                  , "https://www.spritle.com/blog/feed/"                                                      , "ai-updates"),  # 1d ago
    ("TechSpective - AI"                             , "https://techspective.net/category/technology/artificial-intelligence/feed/"              , "ai-updates"),  # 17d ago
    ("TechTalks"                                     , "https://bdtechtalks.com/feed/"                                                           , "ai-updates"),  # 5d ago
    ("The Algorithmic Bridge"                        , "https://thealgorithmicbridge.substack.com/feed"                                          , "ai-updates"),  # 1d ago
    ("The Conversation - AI"                         , "https://theconversation.com/topics/artificial-intelligence-ai-90/articles.atom"          , "ai-updates"),  # 1d ago
    ("THE DECODER"                                   , "https://the-decoder.com/feed/"                                                           , "ai-updates"),  # 0d ago
    ("The Guardian - AI"                             , "https://www.theguardian.com/technology/artificialintelligenceai/rss"                     , "ai-updates"),  # 0d ago
    ("The Indian Express - AI"                       , "https://indianexpress.com/section/technology/artificial-intelligence/feed/"              , "ai-updates"),  # 0d ago
    ("The Intrinsic Perspective"                     , "https://www.theintrinsicperspective.com/feed/"                                           , "ai-updates"),  # 2d ago
    ("The New York Times - AI"                       , "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/spotlight/artificial-intelligence/rss.xml", "ai-updates"),  # 0d ago
    ("The Next Web (Neural)"                         , "https://thenextweb.com/neural/feed"                                                      , "ai-updates"),  # 0d ago
    ("The Register – AI"                             , "https://www.theregister.com/software/ai_ml/headlines.atom"                               , "ai-updates"),  # 0d ago
    ("The Verge AI"                                  , "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"                       , "ai-updates"),  # 0d ago
    ("The Verge Tech"                                , "https://www.theverge.com/rss/tech/index.xml"                                             , "ai-updates"),  # 0d ago
    ("The Verge – All Posts"                         , "https://www.theverge.com/rss/index.xml"                                                  , "ai-updates"),  # 0d ago
    ("TheSequence"                                   , "https://thesequence.substack.com/feed"                                                   , "ai-updates"),  # 2d ago
    ("Vectra AI Blog"                                , "https://www.vectra.ai/blog/rss.xml"                                                      , "ai-updates"),  # 2d ago
    ("viAct.ai Blog"                                 , "https://www.viact.ai/blog-feed.xml"                                                      , "ai-updates"),  # 1d ago
    ("Visual Studio Magazine"                        , "https://visualstudiomagazine.com/rss-feeds/news.aspx"                                    , "ai-updates"),  # 1d ago
    ("Windows Blog"                                  , "https://blogs.windows.com/feed"                                                          , "ai-updates"),  # 0d ago
    ("WIRED - Artificial Intelligence"               , "https://www.wired.com/feed/tag/ai/latest/rss"                                            , "ai-updates"),  # 0d ago
    ("Yseop Blog"                                    , "https://yseop.com/category/blog/feed/"                                                   , "ai-updates"),  # 16d ago

    #  AI Business: funding, M&A, enterprise, policy, markets ──────────────────
    ("Adweek - AI"                                   , "https://www.adweek.com/category/artificial-intelligence/feed/"                           , "ai-business"),  # 1d ago
    ("AI Business"                                   , "https://aibusiness.com/rss.xml"                                                          , "ai-business"),  # 0d ago
    ("AI Now Institute"                              , "https://ainowinstitute.org/category/news/feed"                                           , "ai-business"),  # 10d ago
    ("AI – AI-TechPark"                              , "https://ai-techpark.com/category/ai/feed/"                                               , "ai-business"),  # 1d ago
    ("Artificial Lawyer"                             , "https://www.artificiallawyer.com/feed/"                                                  , "ai-business"),  # 1d ago
    ("Big Data Analytics News - AI"                  , "https://bigdataanalyticsnews.com/category/artificial-intelligence/feed/"                 , "ai-business"),  # 15d ago
    ("Bloomberg Technology"                          , "https://feeds.bloomberg.com/technology/news.rss"                                         , "ai-business"),  # 0d ago
    ("Business Insider"                              , "https://feeds.businessinsider.com/custom/all"                                            , "ai-business"),  # 0d ago
    ("Business Latest (WIRED)"                       , "https://www.wired.com/feed/category/business/latest/rss"                                 , "ai-business"),  # 0d ago
    ("CNBC Tech"                                     , "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910"     , "ai-business"),  # 0d ago
    ("Computerworld - AI"                            , "https://www.computerworld.com/artificial-intelligence/feed/"                             , "ai-business"),  # 0d ago
    ("Crunchbase News"                               , "https://news.crunchbase.com/feed"                                                        , "ai-business"),  # 0d ago
    ("Crunchbase News - AI"                          , "https://news.crunchbase.com/sections/ai/feed/"                                           , "ai-business"),  # 0d ago
    ("Databricks Blog"                               , "https://www.databricks.com/feed"                                                         , "ai-business"),  # 0d ago
    ("Datafloq"                                      , "https://datafloq.com/feed/?post_type=post"                                               , "ai-business"),  # 3d ago
    ("Deep Tech – Tech.eu"                           , "https://tech.eu/category/deep-tech/feed"                                                 , "ai-business"),  # 2d ago
    ("Edmonton Journal - AI"                         , "https://edmontonjournal.com/tag/artificial-intelligence/feed.xml"                        , "ai-business"),  # 16d ago
    ("eWeek - AI"                                    , "https://www.eweek.com/feed/"                                                             , "ai-business"),  # 0d ago
    ("Fast Company - AI"                             , "https://www.fastcompany.com/section/artificial-intelligence/rss"                         , "ai-business"),  # 1d ago
    ("Federal News Network - AI"                     , "https://federalnewsnetwork.com/category/technology-main/artificial-intelligence/feed/"   , "ai-business"),  # 0d ago
    ("Financial Times - AI"                          , "https://www.ft.com/artificial-intelligence?format=rss"                                   , "ai-business"),  # 0d ago
    ("Forrester – AI"                                , "https://www.forrester.com/blogs/category/artificial-intelligence-ai/feed"                , "ai-business"),  # 1d ago
    ("France 24 - AI"                                , "https://www.france24.com/en/tag/artificial-intelligence/rss"                             , "ai-business"),  # 0d ago
    ("Global News – AI"                              , "https://globalnews.ca/tag/artificial-intelligence/feed"                                  , "ai-business"),  # 3d ago
    ("Government Technology - AI"                    , "https://www.govtech.com/artificial-intelligence.rss"                                     , "ai-business"),  # 0d ago
    ("IEEE Spectrum – AI"                            , "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss"                       , "ai-business"),  # 0d ago
    ("InfoWorld - AI"                                , "https://www.infoworld.com/artificial-intelligence/feed/"                                 , "ai-business"),  # 0d ago
    ("International Business Times"                  , "https://www.ibtimes.com/rss"                                                             , "ai-business"),  # 0d ago
    ("Meta News"                                     , "https://about.fb.com/feed"                                                               , "ai-business"),  # 2d ago
    ("Microsoft - AI"                                , "https://news.microsoft.com/source/topics/ai/feed/"                                       , "ai-business"),  # 11d ago
    ("Microsoft Research"                            , "https://www.microsoft.com/en-us/research/feed/"                                          , "ai-business"),  # 8d ago
    ("Mint - AI"                                     , "https://www.livemint.com/rss/AI"                                                         , "ai-business"),  # 0d ago
    ("NYT Technology"                                , "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"                             , "ai-business"),  # 0d ago
    ("Rest of World – Latest Stories"                , "https://restofworld.org/feed/latest"                                                     , "ai-business"),  # 0d ago
    ("Reuters via Google News"                       , "https://news.google.com/rss/search?q=site%3Areuters.com+technology&hl=en-US&gl=US&ceid=US%3Aen", "ai-business"),  # 0d ago
    ("Robotics – Tech.eu"                            , "https://tech.eu/category/robotics/feed"                                                  , "ai-business"),  # 12d ago
    ("Scripps News - AI"                             , "https://www.scrippsnews.com/science-and-tech/artificial-intelligence.rss"                , "ai-business"),  # 12d ago
    ("Silicon Republic"                              , "https://www.siliconrepublic.com/feed"                                                    , "ai-business"),  # 1d ago
    ("Tech Monitor"                                  , "https://techmonitor.ai/feed"                                                             , "ai-business"),  # 1d ago
    ("TechCrunch (main)"                             , "https://techcrunch.com/feed/"                                                            , "ai-business"),  # 0d ago
    ("Techmeme"                                      , "https://www.techmeme.com/feed.xml"                                                       , "ai-business"),  # 0d ago
    ("WSJ Tech"                                      , "https://feeds.content.dowjones.io/public/rss/RSSWSJD"                                    , "ai-business"),  # 0d ago
    ("ZDNET – AI"                                    , "https://www.zdnet.com/topic/artificial-intelligence/rss.xml"                             , "ai-business"),  # 0d ago
    ("ZDNET – Big Data"                              , "https://www.zdnet.com/topic/big-data/rss.xml"                                            , "ai-business"),  # 0d ago

    #  AI Dev: tools, libraries, SDKs, tutorials, infrastructure ───────────────
    ("Analytics Vidhya Blog"                         , "https://www.analyticsvidhya.com/feed/"                                                   , "ai-dev"),  # 0d ago
    ("AWS Blog - Machine Learning/AI"                , "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/feed/"    , "ai-dev"),  # 1d ago
    ("AWS DevOps"                                    , "https://aws.amazon.com/blogs/devops/feed/"                                               , "ai-dev"),  # 15d ago
    ("AWS Machine Learning"                          , "https://aws.amazon.com/blogs/machine-learning/feed/"                                     , "ai-dev"),  # 1d ago
    ("Blog – PyImageSearch"                          , "https://pyimagesearch.com/blog/feed"                                                     , "ai-dev"),  # 5d ago
    ("ByteByteGo"                                    , "https://blog.bytebytego.com/feed"                                                        , "ai-dev"),  # 0d ago
    ("Databricks Docs"                               , "https://docs.databricks.com/aws/en/feed.xml"                                             , "ai-dev"),  # 2d ago
    ("DebuggerCafe"                                  , "https://debuggercafe.com/feed/"                                                          , "ai-dev"),  # 5d ago
    ("Deephaven Blog"                                , "https://deephaven.io/blog/rss.xml"                                                       , "ai-dev"),  # 2d ago
    ("DEV Community"                                 , "https://dev.to/feed"                                                                     , "ai-dev"),  # 0d ago
    ("Explosion"                                     , "https://explosion.ai/feed"                                                               , "ai-dev"),  # 25d ago
    ("Gradient Flow"                                 , "https://gradientflow.com/feed/"                                                          , "ai-dev"),  # 0d ago
    ("Hacker News Front Page"                        , "https://hnrss.org/frontpage"                                                             , "ai-dev"),  # 0d ago
    ("HashiCorp Blog"                                , "https://www.hashicorp.com/blog/feed.xml"                                                 , "ai-dev"),  # 11d ago
    ("Hugging Face Blog"                             , "https://huggingface.co/blog/feed.xml"                                                    , "ai-dev"),  # 0d ago
    ("InfoQ – AI, ML & Data Engineering"             , "https://feed.infoq.com/ai-ml-data-eng/"                                                  , "ai-dev"),  # 1d ago
    ("Interconnects"                                 , "https://www.interconnects.ai/feed"                                                       , "ai-dev"),  # 3d ago
    ("KDnuggets"                                     , "https://www.kdnuggets.com/feed"                                                          , "ai-dev"),  # 1d ago
    ("Kubernetes Blog"                               , "https://kubernetes.io/feed.xml"                                                          , "ai-dev"),  # 0d ago
    ("LangChain"                                     , "https://blog.langchain.dev/rss/"                                                         , "ai-dev"),  # 1d ago
    ("Latent Space"                                  , "https://www.latent.space/feed"                                                           , "ai-dev"),  # 0d ago
    ("Machine Learning Mastery Blog"                 , "https://machinelearningmastery.com/blog/feed/"                                           , "ai-dev"),  # 16d ago
    ("Max Woolf's Blog"                              , "https://minimaxir.com/post/index.xml"                                                    , "ai-dev"),  # 21d ago
    ("Meta Engineering"                              , "https://engineering.fb.com/feed"                                                         , "ai-dev"),  # 2d ago
    ("Nanonets Blog"                                 , "https://nanonets.com/blog/rss"                                                           , "ai-dev"),  # 7d ago
    ("Nicholas Carlini"                              , "https://nicholas.carlini.com/writing/feed.xml"                                           , "ai-dev"),  # 12d ago
    ("NVIDIA Developer"                              , "https://developer.nvidia.com/blog/feed"                                                  , "ai-dev"),  # 3d ago
    ("Product Hunt"                                  , "https://www.producthunt.com/feed"                                                        , "ai-dev"),  # 0d ago
    ("R-bloggers"                                    , "https://feeds.feedburner.com/RBloggers"                                                  , "ai-dev"),  # 0d ago
    ("Replicate Blog"                                , "https://replicate.com/blog/rss"                                                          , "ai-dev"),  # 25d ago
    ("Simon Willison's Weblog"                       , "https://simonwillison.net/atom/everything/"                                              , "ai-dev"),  # 0d ago
    ("Stack Overflow Blog"                           , "https://stackoverflow.blog/feed/"                                                        , "ai-dev"),  # 1d ago
    ("The New Stack"                                 , "https://thenewstack.io/feed"                                                             , "ai-dev"),  # 0d ago
    ("Towards AI – Medium"                           , "https://pub.towardsai.net/feed"                                                          , "ai-dev"),  # 0d ago
    ("Towards Data Science"                          , "https://towardsdatascience.com/feed"                                                     , "ai-dev"),  # 0d ago
    ("Wolfram Blog"                                  , "https://blog.wolfram.com/feed/"                                                          , "ai-dev"),  # 9d ago

    #  Security: AI-driven threats, breaches, vulnerability research ───────────
    ("Dark Reading"                                  , "https://www.darkreading.com/rss.xml"                                                     , "security"),  # 0d ago
    ("Hacker Noon – AI"                              , "https://hackernoon.com/tagged/ai/feed"                                                   , "security"),  # 0d ago
    ("Infosecurity Magazine"                         , "https://www.infosecurity-magazine.com/rss/news/"                                         , "security"),  # 1d ago
    ("Krebs on Security"                             , "https://krebsonsecurity.com/feed/"                                                       , "security"),  # 1d ago
    ("Microsoft Security"                            , "https://api.msrc.microsoft.com/update-guide/rss"                                         , "security"),  # 0d ago
    ("Palo Alto Unit 42"                             , "https://unit42.paloaltonetworks.com/feed/"                                               , "security"),  # 0d ago
    ("The Hacker News"                               , "https://feeds.feedburner.com/TheHackersNews"                                             , "security"),  # 0d ago
    ("The Verge Security"                            , "https://www.theverge.com/rss/cyber-security/index.xml"                                   , "security"),  # 2d ago

]
