"""
feeds.py — RSS feed sources for the AI Daily newsletter pipeline.

Each entry: (name, url)
No sector assignment — category is determined by the LLM summarizer based on content.
"""

# =============================================================================
# WEB_SOURCES — Direct blog page scraping (second layer)
#
# For AI labs that publish no public RSS feed. The web_feed.py scraper fetches
# each listing page, extracts article links + dates, and filters to edition dates.
# xAI (x.ai) and Perplexity block scrapers (403) — covered via Google News RSS.
# =============================================================================
WEB_SOURCES: list[tuple[str, str]] = [
    ("Anthropic Blog",  "https://www.anthropic.com/news"),
    ("Mistral AI Blog", "https://mistral.ai/news"),
    ("Cursor Blog",     "https://www.cursor.com/blog"),
    ("Windsurf Blog",   "https://windsurf.com/blog"),
]


FEEDS = [
    # ── Official lab RSS feeds ──────────────────────────────────────────────
    ("Hugging Face Blog"                             , "https://huggingface.co/blog/feed.xml"),
    ("OpenAI News"                                   , "https://openai.com/news/rss.xml"),
    ("Google DeepMind"                               , "https://deepmind.google/blog/rss.xml"),
    ("Google AI Blog"                                , "https://blog.google/technology/ai/rss/"),
    ("Google Research"                               , "https://research.google/blog/rss/"),
    ("Microsoft Research"                            , "https://www.microsoft.com/en-us/research/blog/feed/"),
    ("NVIDIA Blog"                                   , "https://blogs.nvidia.com/feed/"),
    ("Apple ML"                                      , "https://machinelearning.apple.com/rss.xml"),
    ("AWS News Blog - AI"                            , "https://aws.amazon.com/blogs/aws/category/artificial-intelligence/feed/"),
    ("Google Cloud AI Blog"                          , "https://cloud.google.com/blog/products/ai-machine-learning/rss"),
    ("Azure AI Blog"                                 , "https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/bg-p/Azure-AI-Services-Blog/rss"),
    ("Berkeley AI (BAIR)"                            , "https://bair.berkeley.edu/blog/feed.xml"),
    ("CMU ML Blog"                                   , "https://blog.ml.cmu.edu/feed"),
    ("MIT AI News"                                   , "https://news.mit.edu/topic/artificial-intelligence2/feed"),
    ("GitHub Blog"                                   , "https://github.blog/feed/"),
    ("DeepMind Blog"                                 , "https://deepmind.com/blog/feed/basic/"),
    # ── Google News: company model releases ─────────────────────────────────
    ("OpenAI Model News"                             , "https://news.google.com/rss/search?q=OpenAI+model+release+GPT&hl=en-US&gl=US&ceid=US:en"),
    ("Anthropic News"                                , "https://news.google.com/rss/search?q=Anthropic+Claude+model+release&hl=en-US&gl=US&ceid=US:en"),
    ("Google Gemini News"                            , "https://news.google.com/rss/search?q=Google+Gemini+model+AI+release&hl=en-US&gl=US&ceid=US:en"),
    ("xAI / Grok News"                               , "https://news.google.com/rss/search?q=xAI+Grok+model+release&hl=en-US&gl=US&ceid=US:en"),
    ("DeepSeek News"                                 , "https://news.google.com/rss/search?q=DeepSeek+AI+model&hl=en-US&gl=US&ceid=US:en"),
    ("Meta AI / Llama News"                          , "https://news.google.com/rss/search?q=Meta+AI+Llama+model&hl=en-US&gl=US&ceid=US:en"),
    ("Mistral AI News"                               , "https://news.google.com/rss/search?q=Mistral+AI+model+release&hl=en-US&gl=US&ceid=US:en"),
    ("Perplexity AI News"                            , "https://news.google.com/rss/search?q=Perplexity+AI+release&hl=en-US&gl=US&ceid=US:en"),
    ("Kimi / Moonshot AI News"                       , "https://news.google.com/rss/search?q=Moonshot+Kimi+AI+model&hl=en-US&gl=US&ceid=US:en"),
    ("Cohere News"                                   , "https://news.google.com/rss/search?q=Cohere+AI+model&hl=en-US&gl=US&ceid=US:en"),
    # ── Google News: developer topics ───────────────────────────────────────
    ("AI Model Releases"                             , "https://news.google.com/rss/search?q=AI+model+release+LLM&hl=en-US&gl=US&ceid=US:en"),
    ("RAG & Agent Frameworks"                        , "https://news.google.com/rss/search?q=RAG+agent+framework+LLM&hl=en-US&gl=US&ceid=US:en"),
    ("Open Source LLM"                               , "https://news.google.com/rss/search?q=open+source+LLM+model+weights&hl=en-US&gl=US&ceid=US:en"),
    ("AI Coding Tools"                               , "https://news.google.com/rss/search?q=AI+coding+tool+Cursor+Windsurf+Copilot&hl=en-US&gl=US&ceid=US:en"),
    ("Cursor News"                                   , "https://news.google.com/rss/search?q=Cursor+AI+editor+feature&hl=en-US&gl=US&ceid=US:en"),
    ("Windsurf News"                                 , "https://news.google.com/rss/search?q=Windsurf+Codeium+AI+coding&hl=en-US&gl=US&ceid=US:en"),

    # ── General AI news ──────────────────────────────────────────────────────
    ("404 Media"                                     , "https://www.404media.co/rss"),
    ("Ahead of AI"                                   , "https://magazine.sebastianraschka.com/feed"),
    ("AI 2 People"                                   , "https://ai2people.com/feed/"),
    ("AI Accelerator Institute"                      , "https://aiacceleratorinstitute.com/rss/"),
    ("AI for Good Blog"                              , "https://aiforgood.itu.int/feed/"),
    ("AI Insider"                                    , "https://theaiinsider.tech/feed/"),
    ("AI News"                                       , "https://www.artificialintelligence-news.com/feed/"),
    ("AI Snake Oil"                                  , "https://aisnakeoil.substack.com/feed"),
    ("AI Time Journal"                               , "https://www.aitimejournal.com/feed/"),
    ("AI Weekly"                                     , "https://aiweekly.co/issues.rss"),
    ("AI – SiliconANGLE"                             , "https://siliconangle.com/category/ai/feed"),
    ("AIhub"                                         , "https://aihub.org/feed/?cat=-473"),
    ("AIModels.fyi"                                  , "https://aimodels.substack.com/feed"),
    ("Ars Technica"                                  , "https://feeds.arstechnica.com/arstechnica/index"),
    ("Ars Technica - AI"                             , "https://arstechnica.com/ai/feed/"),
    ("Artificial Intelligence – Futurism"            , "https://futurism.com/categories/ai-artificial-intelligence/feed"),
    ("Artificial Intelligence – TechRepublic"        , "https://www.techrepublic.com/rssfeeds/topic/artificial-intelligence/"),
    ("Artificial intelligence – The Conversation (EU)", "https://theconversation.com/europe/topics/artificial-intelligence-ai-90/articles.atom"),
    ("Chain of Thought (every.to)"                   , "https://every.to/chain-of-thought/feed.xml"),
    ("Cisco Blogs - AI"                              , "https://blogs.cisco.com/ai/feed"),
    ("EE Times"                                      , "https://www.eetimes.com/feed"),
    ("Engadget"                                      , "https://www.engadget.com/rss.xml"),
    ("Gizmodo"                                       , "https://gizmodo.com/rss"),
    ("HealthTech Magazine"                           , "https://feeds.feedburner.com/HealthTechMagazine"),
    ("Import AI (Beehiiv)"                           , "https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml"),
    ("Import AI (Jack Clark)"                        , "https://importai.substack.com/feed"),
    ("Just AI News"                                  , "https://justainews.com/feed/"),
    ("Live Science - AI"                             , "https://www.livescience.com/feeds/tag/artificial-intelligence"),
    ("Machine learning – Nature"                     , "https://www.nature.com/subjects/machine-learning.rss"),
    ("MarkTechPost"                                  , "https://www.marktechpost.com/feed/"),
    ("MIRI Blog"                                     , "https://intelligence.org/feed/"),
    ("MIT News – Machine Learning"                   , "https://news.mit.edu/topic/mitmachine-learning-rss.xml"),
    ("MIT Tech Review"                               , "https://www.technologyreview.com/feed/"),
    ("MIT Tech Review AI"                            , "https://www.technologyreview.com/topic/artificial-intelligence/feed/"),
    ("New Scientist – Technology"                    , "https://www.newscientist.com/subject/technology/feed/"),
    ("News on AI/ML – TechXplore"                    , "https://techxplore.com/rss-feed/machine-learning-ai-news/"),
    ("News on AI/ML – TechXplore (phys.org)"         , "https://phys.org/rss-feed/technology-news/machine-learning-ai/"),
    ("NVIDIA Developer"                              , "https://developer.nvidia.com/blog/feed"),
    ("O'Reilly Media - AI & ML"                      , "https://www.oreilly.com/radar/topics/ai-ml/feed/index.xml"),
    ("One Useful Thing"                              , "https://www.oneusefulthing.org/feed"),
    ("Quanta Magazine"                               , "https://api.quantamagazine.org/feed"),
    ("Robotics Research News – ScienceDaily"         , "https://www.sciencedaily.com/rss/computers_math/robotics.xml"),
    ("Science News - AI"                             , "https://www.sciencenews.org/topic/artificial-intelligence/feed"),
    ("ScienceDaily - AI News"                        , "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml"),
    ("Scientific American"                           , "http://rss.sciam.com/ScientificAmerican-Global"),
    ("TechTalks"                                     , "https://bdtechtalks.com/feed/"),
    ("The Algorithmic Bridge"                        , "https://thealgorithmicbridge.substack.com/feed"),
    ("The Conversation - AI"                         , "https://theconversation.com/topics/artificial-intelligence-ai-90/articles.atom"),
    ("THE DECODER"                                   , "https://the-decoder.com/feed/"),
    ("The Guardian - AI"                             , "https://www.theguardian.com/technology/artificialintelligenceai/rss"),
    ("The Intrinsic Perspective"                     , "https://www.theintrinsicperspective.com/feed/"),
    ("The New York Times - AI"                       , "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/spotlight/artificial-intelligence/rss.xml"),
    ("The Next Web (Neural)"                         , "https://thenextweb.com/neural/feed"),
    ("The Register – AI"                             , "https://www.theregister.com/software/ai_ml/headlines.atom"),
    ("The Verge AI"                                  , "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"),
    ("The Verge Tech"                                , "https://www.theverge.com/rss/tech/index.xml"),
    ("TheSequence"                                   , "https://thesequence.substack.com/feed"),
    ("WIRED - Artificial Intelligence"               , "https://www.wired.com/feed/tag/ai/latest/rss"),

    # ── Business, funding, policy ────────────────────────────────────────────
    ("Adweek - AI"                                   , "https://www.adweek.com/category/artificial-intelligence/feed/"),
    ("AI Business"                                   , "https://aibusiness.com/rss.xml"),
    ("AI Now Institute"                              , "https://ainowinstitute.org/category/news/feed"),
    ("Artificial Lawyer"                             , "https://www.artificiallawyer.com/feed/"),
    ("Bloomberg Technology"                          , "https://feeds.bloomberg.com/technology/news.rss"),
    ("Business Insider"                              , "https://feeds.businessinsider.com/custom/all"),
    ("Business Latest (WIRED)"                       , "https://www.wired.com/feed/category/business/latest/rss"),
    ("CNBC Tech"                                     , "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910"),
    ("Computerworld - AI"                            , "https://www.computerworld.com/artificial-intelligence/feed/"),
    ("Crunchbase News"                               , "https://news.crunchbase.com/feed"),
    ("Crunchbase News - AI"                          , "https://news.crunchbase.com/sections/ai/feed/"),
    ("Databricks Blog"                               , "https://www.databricks.com/feed"),
    ("Deep Tech – Tech.eu"                           , "https://tech.eu/category/deep-tech/feed"),
    ("eWeek - AI"                                    , "https://www.eweek.com/feed/"),
    ("Fast Company - AI"                             , "https://www.fastcompany.com/section/artificial-intelligence/rss"),
    ("Federal News Network - AI"                     , "https://federalnewsnetwork.com/category/technology-main/artificial-intelligence/feed/"),
    ("Financial Times - AI"                          , "https://www.ft.com/artificial-intelligence?format=rss"),
    ("Forrester – AI"                                , "https://www.forrester.com/blogs/category/artificial-intelligence-ai/feed"),
    ("France 24 - AI"                                , "https://www.france24.com/en/tag/artificial-intelligence/rss"),
    ("Government Technology - AI"                    , "https://www.govtech.com/artificial-intelligence.rss"),
    ("IEEE Spectrum – AI"                            , "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss"),
    ("InfoWorld - AI"                                , "https://www.infoworld.com/artificial-intelligence/feed/"),
    ("Meta News"                                     , "https://about.fb.com/feed"),
    ("Microsoft - AI"                                , "https://news.microsoft.com/source/topics/ai/feed/"),
    ("NYT Technology"                                , "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"),
    ("Rest of World – Latest Stories"                , "https://restofworld.org/feed/latest"),
    ("Reuters via Google News"                       , "https://news.google.com/rss/search?q=site%3Areuters.com+technology&hl=en-US&gl=US&ceid=US%3Aen"),
    ("Silicon Republic"                              , "https://www.siliconrepublic.com/feed"),
    ("Tech Monitor"                                  , "https://techmonitor.ai/feed"),
    ("TechCrunch (main)"                             , "https://techcrunch.com/feed/"),
    ("Techmeme"                                      , "https://www.techmeme.com/feed.xml"),
    ("WSJ Tech"                                      , "https://feeds.content.dowjones.io/public/rss/RSSWSJD"),
    ("ZDNET – AI"                                    , "https://www.zdnet.com/topic/artificial-intelligence/rss.xml"),

    # ── Developer tools, libraries, tutorials ───────────────────────────────
    ("Analytics Vidhya Blog"                         , "https://www.analyticsvidhya.com/feed/"),
    ("AssemblyAI Blog"                               , "https://www.assemblyai.com/blog/feed/"),
    ("AWS Blog - Machine Learning/AI"                , "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/feed/"),
    ("AWS Machine Learning"                          , "https://aws.amazon.com/blogs/machine-learning/feed/"),
    ("ByteByteGo"                                    , "https://blog.bytebytego.com/feed"),
    ("Databricks Docs"                               , "https://docs.databricks.com/aws/en/feed.xml"),
    ("DEV Community"                                 , "https://dev.to/feed"),
    ("fast.ai"                                       , "https://www.fast.ai/feed.xml"),
    ("Gradient Flow"                                 , "https://gradientflow.com/feed/"),
    ("Hacker News Front Page"                        , "https://hnrss.org/frontpage"),
    ("Hacker News – Ask HN"                          , "https://hnrss.org/ask"),
    ("InfoQ – AI, ML & Data Engineering"             , "https://feed.infoq.com/ai-ml-data-eng/"),
    ("Interconnects"                                 , "https://www.interconnects.ai/feed"),
    ("KDnuggets"                                     , "https://www.kdnuggets.com/feed"),
    ("LangChain"                                     , "https://blog.langchain.dev/rss/"),
    ("Latent Space"                                  , "https://www.latent.space/feed"),
    ("Lightning AI Blog"                             , "https://lightning.ai/blog/feed/"),
    ("Medium – AI tag"                               , "https://medium.com/feed/tag/artificial-intelligence"),
    ("Medium – LLM tag"                              , "https://medium.com/feed/tag/llm"),
    ("Medium – Machine Learning tag"                 , "https://medium.com/feed/tag/machine-learning"),
    ("Meta Engineering"                              , "https://engineering.fb.com/feed"),
    ("MLOps Community"                               , "https://mlops.community/feed/"),
    ("NVIDIA Blog"                                   , "https://feeds.feedburner.com/nvidiablog"),
    ("Product Hunt"                                  , "https://www.producthunt.com/feed"),
    ("Replicate Blog"                                , "https://replicate.com/blog/rss"),
    ("Simon Willison's Weblog"                       , "https://simonwillison.net/atom/everything/"),
    ("Stack Overflow Blog"                           , "https://stackoverflow.blog/feed/"),
    ("The New Stack"                                 , "https://thenewstack.io/feed"),
    ("Towards AI – Medium"                           , "https://pub.towardsai.net/feed"),
    ("Towards Data Science"                          , "https://towardsdatascience.com/feed"),

    # ── Security ─────────────────────────────────────────────────────────────
    ("Dark Reading"                                  , "https://www.darkreading.com/rss.xml"),
    ("Hacker Noon – AI"                              , "https://hackernoon.com/tagged/ai/feed"),
    ("Infosecurity Magazine"                         , "https://www.infosecurity-magazine.com/rss/news/"),
    ("Krebs on Security"                             , "https://krebsonsecurity.com/feed/"),
    ("Microsoft Security"                            , "https://api.msrc.microsoft.com/update-guide/rss"),
    ("Palo Alto Unit 42"                             , "https://unit42.paloaltonetworks.com/feed/"),
    ("The Hacker News"                               , "https://feeds.feedburner.com/TheHackersNews"),
    ("The Verge Security"                            , "https://www.theverge.com/rss/cyber-security/index.xml"),
]
